### PR TITLE
Add more resources

### PR DESCRIPTION
**Pull request by Doishy**

### CODE REVIEW

**Comment by angrybacon** [comment]
I think they should update/fix the link to the Wiki

```diff
-http://https://ddftwiki.netlify.app
+https://ddft.wiki
```

And if they want to add a link to the original article near the top: https://ddft.wiki/articles/2020/03/12/pretty-mean-deck/

**Comment by Doishy** [comment]
What was left on this @angrybacon ?

**Comment by angrybacon** [comment]
> What was left on this @angrybacon ?

PM'd LarsonZ over Discord to fix the links to the Wiki in the Chinese article but still no reply.

**Comment by Doishy** [comment]
Added moar sauce. 
I think if no response from LarsonZ let's just deploy this now

**Comment by angrybacon** [comment]
> I think if no response from LarsonZ let's just deploy this now

They said they would do it (July 15th) so I'll check whether that's done yet. If not I'll remove the link and open another PR so nothing gets stuck forever.

Btw, this is why PRs and commits should be as small and canonical as possible (easy revert, easy reviews).

**Comment by Doishy** [comment]
Issue #108 raised to track link update. Please do final checks and deploy PR.

**Review by angrybacon — APPROVED** [review]

**Pull request merged**
